spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/bankingdb
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=A9fYkL2xV7eP0bW8zQ1sN4cR5tM3jH6uD9gE0fG7rY2qJ8wZ1
# 24 hours in milliseconds
jwt.expiration=86400000 

